javafx:
  title: JavaFx & SpringBoot
  appicons: /icon/icon.png
  stage:
    width: 1080
    height: 820
#    style: DECORATED  # javafx.stage.StageStyle [DECORATED, UNDECORATED, TRANSPARENT, UTILITY, UNIFIED]
#    resizable: false
